export const phrasalVerbDialog = {
  id: "phrasal-verb-examples",
  title: "Phrasal Verb Examples",
  description: "62 everyday examples for listening and speaking practice.",
  sentences: [
    "I usually get dressed quickly because I'm often running late.",
    "I usually head out for work around eight.",
    "I usually pick up a coffee on the way to work.",
    "You can drop me off here.",
    "He didn't show up for the meeting.",
    "She set up the meeting room before the meeting.",
    "I'll get back to you about this later.",
    "Reach out if you have any questions.",
    "I missed two classes, so I need to catch up.",
    "I accidentally hung up before she finished speaking.",
    "Please speak up a bit. I can't hear you clearly.",
    "He brought up an interesting point in the meeting.",
    "Please hand in your form at the front desk.",
    "I took on a new project, and I'm in charge of managing it.",
    "The team successfully carried out the plan.",
    "Let's go over your document before the presentation.",
    "I can't figure out what he was hinting at.",
    "I had to deal with a difficult problem at work today.",
    "Last week was tough, but I finally got through it.",
    "Let's break the problem down into smaller steps.",
    "My car is running out of gas.",
    "I've got to sort out my desktop.",
    "A problem came up last night.",
    "We need to come up with a solution as soon as possible.",
    "I can't put up with this noise anymore.",
    "Let's get together for dinner sometime.",
    "We met up after work.",
    "Do you want to go out tonight?",
    "How are you fitting in at your new job?",
    "Have you settled into your new job yet?",
    "I get along with my new neighbours.",
    "She fell out with her friend over a small misunderstanding.",
    "It took her a long time to open up about her worries.",
    "Let's move on to the next topic.",
    "Where's the checkout?",
    "Let's set off early tomorrow morning to avoid traffic.",
    "The weather suddenly turned bad, so we decided to turn back.",
    "I feel like I'm coming down with a cold.",
    "It took her months to get over the breakup.",
    "I'm over it.",
    "She worked too much and burned out.",
    "He passed out in the heat.",
    "He keeps making excuses, and it's wearing me down.",
    "Walk slower. I can't keep up with you.",
    "I've got to tidy up my room.",
    "We cleaned up the kitchen after the party.",
    "Please put away your books.",
    "I throw out some of my stuff every time I move.",
    "I've got to fix up my resume before applying for jobs.",
    "I'll pay you back on Friday.",
    "I'm saving up to buy a new laptop.",
    "We splashed out on dinner for our anniversary.",
    "I'm trying to cut back on coffee.",
    "These small costs add up quickly.",
    "Please go on. I'm listening.",
    "Carry on with your work.",
    "I came across an old friend in the park.",
    "We were going to go out, but we ended up staying at home.",
    "It turned out to be an error in the database.",
    "We had to put off the meeting because the manager was sick.",
    "I took up swimming last year.",
    "Hold on, let me check my calendar.",
  ],
};
